### ISSUE TITLE
Question about the environment

### ISSUE THREAD

**Issue by bf-yang** [NUS-HPC-AI-Lab/SGL#2]
Hi, thanks for your great work!

I have followed your current instructions (https://internvl.readthedocs.io/en/latest/get_started/installation.html), install the environment by InternVL.

But still have some errors like this:
![image](https://github.com/user-attachments/assets/145d6f6e-8645-44ec-9367-0302f64ad41a)

Could you please provide details about the environment for this project?
Thanks~

The environment I used is as follow:
Package                   Version
------------------------- -----------
absl-py                   2.1.0
accelerate                0.34.2
addict                    2.4.0
aiofiles                  24.1.0
aiohappyeyeballs          2.4.4
aiohttp                   3.11.11
aiosignal                 1.3.2
altair                    5.5.0
annotated-types           0.7.0
anyio                     4.7.0
async-timeout             5.0.1
attrs                     24.3.0
beautifulsoup4            4.12.3
bitsandbytes              0.42.0
blinker                   1.9.0
cachetools                5.5.0
certifi                   2024.12.14
charset-normalizer        3.4.1
click                     8.1.8
colorama                  0.4.6
contourpy                 1.3.0
cycler                    0.12.1
decord                    0.6.0
deepspeed                 0.16.2
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.2
fastapi                   0.115.6
ffmpy                     0.5.0
filelock                  3.16.1
fonttools                 4.55.3
frozenlist                1.5.0
fsspec                    2024.12.0
future                    1.0.0
gdown                     5.2.0
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    3.35.2
gradio_client             0.2.9
grpcio                    1.68.1
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.27.0
idna                      3.10
imageio                   2.36.1
importlib_metadata        8.5.0
importlib_resources       6.4.5
Jinja2                    3.1.5
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
latex2mathml              3.77.0
linkify-it-py             2.0.3
Markdown                  3.7
markdown-it-py            2.2.0
markdown2                 2.5.2
MarkupSafe                3.0.2
matplotlib                3.9.4
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mmcls                     0.25.0
mmcv-full                 1.6.2
mmsegmentation            0.30.0
model-index               0.1.11
mpmath                    1.3.0
msgpack                   1.1.0
multidict                 6.1.0
narwhals                  1.20.1
networkx                  3.2.1
ninja                     1.11.1.3
numpy                     1.26.4
nvidia-cublas-cu12        12.4.5.8
nvidia-cuda-cupti-cu12    12.4.127
nvidia-cuda-nvrtc-cu12    12.4.127
nvidia-cuda-runtime-cu12  12.4.127
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.2.1.3
nvidia-curand-cu12        10.3.5.147
nvidia-cusolver-cu12      11.6.1.9
nvidia-cusparse-cu12      12.3.1.170
nvidia-nccl-cu12          2.21.5
nvidia-nvjitlink-cu12     12.4.127
nvidia-nvtx-cu12          12.4.127
opencv-python             4.10.0.84
opendatalab               0.0.10
openmim                   0.3.9
openxlab                  0.0.11
ordered-set               4.1.0
orjson                    3.10.13
packaging                 24.2
pandas                    2.2.3
peft                      0.10.0
pillow                    11.0.0
pip                       24.2
platformdirs              4.3.6
prettytable               3.12.0
propcache                 0.2.1
protobuf                  5.29.2
psutil                    6.1.1
py-cpuinfo                9.0.0
pyarrow                   18.1.0
pycocoevalcap             1.2
pycocotools               2.0.8
pycryptodome              3.21.0
pydantic                  2.10.4
pydantic_core             2.27.2
pydeck                    0.9.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.2.0
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-multipart          0.0.20
pytz                      2024.2
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.11.6
requests                  2.32.3
rich                      13.9.4
rpds-py                   0.22.3
safetensors               0.4.5
scikit-learn              1.6.0
scipy                     1.13.1
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                75.1.0
shortuuid                 1.0.13
six                       1.17.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.6
starlette                 0.41.3
streamlit                 1.41.1
streamlit-image-select    0.6.0
svgwrite                  1.4.3
sympy                     1.13.1
tabulate                  0.9.0
tenacity                  9.0.0
tensorboard               2.18.0
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
termcolor                 2.5.0
threadpoolctl             3.5.0
timm                      0.9.12
tokenizers                0.15.1
toml                      0.10.2
tomli                     2.2.1
torch                     2.5.1
torchvision               0.20.1
tornado                   6.4.2
tqdm                      4.67.1
transformers              4.37.2
triton                    3.1.0
typing_extensions         4.12.2
tzdata                    2024.2
uc-micro-py               1.0.3
urllib3                   2.3.0
uvicorn                   0.34.0
watchdog                  6.0.0
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
websockets                14.1
Werkzeug                  3.1.3
wheel                     0.44.0
yacs                      0.1.8
yapf                      0.40.1
yarl                      1.18.3
zipp                      3.21.0

**Comment by bf-yang** [comment]
After I upgraded the transformers to 4.45.2, it can solve that problem, but it still has this error:

File "/home/bufang/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2047, in generate
[rank5]:     result = self._sample(
[rank5]: TypeError: _sample() missing 1 required positional argument: 'logits_warper'



![image](https://github.com/user-attachments/assets/eed51cb4-cc25-4459-96d7-6ae4aff3a7b0)

**Comment by wangbo-zhao** [comment]
Hi, sorry for the late reply. I forgot to enable notifications for messages from GitHub. Have you been able to solve this problem? It seems to be related to the version of Transformers.

**Comment by 1563245379** [comment]
same problem for me

**Comment by wangbo-zhao** [comment]
please try transformers==4.44.2
